// Event Types

export type AGUIEventType =
    // Run lifecycle -> A single end to end run for a user request
    | "RUN_STARTED"
    | "RUN_FINISHED"
    | "RUN_ERROR"

    // Steps lifecycle -> A single agents tuen inside a run
    | "STEP_STARTED"
    | "STEP_FINISHED"

    // Text streaming -> How agent sends words to the UI, token by token
    | "TEXT_MESSAGE_START"
    | "TEXT_MESSAGE_CHUNK"
    | "TEXT_MESSAGE_END"

    // State -> Shared memory where all agents can read and write information
    | "STATE_SNAPSHOT"
    | "STATE_DELTA";


// Every single AG-UI event has three fields, no expections
// Frontend uses runId to know which run this event belongs to
interface BaseEvent {
  type: AGUIEventType;
  runId: string;
  timestamp: number;
}

// Lifecycle Events
export interface RunStartedEvent extends BaseEvent {
  type: "RUN_STARTED";
  threadId: string;
}

export interface RunFinishedEvent extends BaseEvent {
  type: "RUN_FINISHED";
}

export interface RunErrorEvent extends BaseEvent {
  type: "RUN_ERROR";
  message: string;
}

// Step Events
export interface StepStartedEvent extends BaseEvent {
  type: "STEP_STARTED";
  stepId: string;
  stepName: string;
}

export interface StepFinishedEvent extends BaseEvent {
  type: "STEP_FINISHED";
  stepId: string;
}

// Text Streaming Events

// Every token generated by agent goes through: START -> CHUNK* -> END
// START -> Tells the UI a new message is beginning create a box for it
// CHUNK -> carries the actual text, token by token as OpenAI streams it
// END -> Tells the UI the message is done, so it can stop waiting for more tokens
// messageId ties all three together, the UI matches CHUNKS to their START using this ID and not by order of arrival

export interface TextMessageStartEvent extends BaseEvent {
  type: "TEXT_MESSAGE_START";
  messageId: string;
  agentName: string;
}

export interface TextMessageChunkEvent extends BaseEvent {
  type: "TEXT_MESSAGE_CHUNK";
  messageId: string;
  delta: string;
}

export interface TextMessageEndEvent extends BaseEvent {
  type: "TEXT_MESSAGE_END";
  messageId: string;
}