// Event Types

export type AGUIEventType =
    // Run lifecycle -> A single end to end run for a user request
    | "RUN_STARTED"
    | "RUN_FINISHED"
    | "RUN_ERROR"

    // Steps lifecycle -> A single agents tuen inside a run
    | "STEP_STARTED"
    | "STEP_FINISHED"

    // Text streaming -> How agent sends words to the UI, token by token
    | "TEXT_MESSAGE_START"
    | "TEXT_MESSAGE_CHUNK"
    | "TEXT_MESSAGE_END"

    // State -> Shared memory where all agents can read and write information
    | "STATE_SNAPSHOT"
    | "STATE_DELTA"

    // HITL
    | "HITL_REQUESTED"
    | "HITL_RESOLVED";


// Every single AG-UI event has three fields, no expections
// Frontend uses runId to know which run this event belongs to
interface BaseEvent {
  type: AGUIEventType;
  runId: string;
  timestamp: number;
}

// Lifecycle Events
export interface RunStartedEvent extends BaseEvent {
  type: "RUN_STARTED";
  threadId: string;
}

export interface RunFinishedEvent extends BaseEvent {
  type: "RUN_FINISHED";
}

export interface RunErrorEvent extends BaseEvent {
  type: "RUN_ERROR";
  message: string;
}

// Step Events
export interface StepStartedEvent extends BaseEvent {
  type: "STEP_STARTED";
  stepId: string;
  stepName: string;
}

export interface StepFinishedEvent extends BaseEvent {
  type: "STEP_FINISHED";
  stepId: string;
}

// Text Streaming Events

// Every token generated by agent goes through: START -> CHUNK* -> END
// START -> Tells the UI a new message is beginning create a box for it
// CHUNK -> carries the actual text, token by token as OpenAI streams it
// END -> Tells the UI the message is done, so it can stop waiting for more tokens
// messageId ties all three together, the UI matches CHUNKS to their START using this ID and not by order of arrival

export interface TextMessageStartEvent extends BaseEvent {
  type: "TEXT_MESSAGE_START";
  messageId: string;
  agentName: string;
}

export interface TextMessageChunkEvent extends BaseEvent {
  type: "TEXT_MESSAGE_CHUNK";
  messageId: string;
  delta: string;
}

export interface TextMessageEndEvent extends BaseEvent {
  type: "TEXT_MESSAGE_END";
  messageId: string;
}

// State Events

// STATE SNAPSHOT -> Sent at the start of a run to initialize UIs state store, contains the entire state object. Also sent after a major reset
export interface DesignState {
  phase: "idle" | "designing" | "awaiting_decision" | "done";
  systemDescription: string;
  agentOutputs: Record<string, string>; // agentName → full text output
  pendingDecision: HITLRequestedEvent["decision"] | null; // current question agent is waiting for answer
  // decisions is a log of every decision made by the agent, the architect reads this
  decisions: Array<{
    decisionId: string;
    question: string;
    chosenLabel: string;
  }>;
}

export interface StateSnapshotEvent extends BaseEvent {
  type: "STATE_SNAPSHOT";
  snapshot: DesignState;
}

export interface JsonPatchOp {
  op: "add" | "replace" | "remove";
  path: string;
  value?: unknown;
}

export interface StateDeltaEvent extends BaseEvent {
  type: "STATE_DELTA";
  delta: JsonPatchOp[];
}

// HITL Events
// Emitted by the agent mid-stream when it hits a decision it cannot resolve
// Frontend will receive a decision card and the stream is kept open while the agent is literally waiting for human input

export interface HITLRequestedEvent extends BaseEvent {
  type: "HITL_REQUESTED";
  decision: {
    id: string;
    question: string;    // what the agent is asking
    context: string;     // why the agent can't proceed without an answer
    options: Array<{
      id: string;
      label: string;
      description: string;
    }>;
  };
}

export interface HITLResolvedPayload {
  runId: string;
  decisionId: string;
  chosenOptionId: string;
}

export type AGUIEvent =
  | RunStartedEvent
  | RunFinishedEvent
  | RunErrorEvent
  | StepStartedEvent
  | StepFinishedEvent
  | TextMessageStartEvent
  | TextMessageChunkEvent
  | TextMessageEndEvent
  | StateSnapshotEvent
  | StateDeltaEvent
  | HITLRequestedEvent;