model_list:
  - model_name: "fast-model"
    litellm_params:
      model: "gpt-4o-mini"
      api_key: "os.environ/OPENAI_API_KEY"
      max_tokens: 256
      temperature: 0.0
  - model_name: "fast-model"
    litellm_params:
      model: "gemini/gemini-2.0-flash"
      api_key: "os.environ/GEMINI_API_KEY"
      max_tokens: 256
      temperature: 0.0
  - model_name: "reasoning-model"
    litellm_params:
      model: "gpt-4o"
      api_key: "os.environ/OPENAI_API_KEY"
      max_tokens: 2048
      temperature: 0.2
  - model_name: "creative-model"
    litellm_params:
      model: "gpt-4o"
      api_key: "os.environ/OPENAI_API_KEY"
      max_tokens: 4096
      temperature: 0.9
  - model_name: "embedding-model"
    litellm_params:
      model: "text-embedding-3-small"
      api_key: "os.environ/OPENAI_API_KEY"

general_settings:
  master_key: "ba357135-ac3d-462c-a4b5-138ac38959ff"

router_settings:
  num_retries: 2
  timeout: 30                             # Any request taking longer than 30 seconds will be considered a failure and triggers fallback
  routing_strategy: "simple-shuffle"